### ISSUE TITLE
How about MS SQL Server?

### ISSUE THREAD

**Issue by emisjerry** [tenie/SQLucky#2]
Hi, MS SQL Server will be supported?

**Comment by tenie** [comment]
[关于如何支持其他关系型数据库](https://github.com/tenie/SQLucky/wiki/%E5%85%B3%E4%BA%8E%E5%A6%82%E4%BD%95%E6%94%AF%E6%8C%81%E5%85%B6%E4%BB%96%E5%85%B3%E7%B3%BB%E5%9E%8B%E6%95%B0%E6%8D%AE%E5%BA%93)
