### ISSUE TITLE
没有提示么？

### ISSUE THREAD

**Issue by ge00111** [tenie/SQLucky#4]
关键字没有提示？
数据库字段没有提示？
执行SQL脚本很慢。。。

**Comment by tenie** [comment]
你好，感谢你的使用反馈.

关于提示问题：关键字，数据库表名，表字段名自动补全是有的，致敬了eclipse的方式，后期版本会添加快捷键自定义功能，让一些隐式的功能可以更直观的看到和可配置.

关于慢：具体查询了多少数据？具体慢多少？和直接在命令行中用命令执行慢多少？ 没有更多的信息我也不好回答. 另外对于GUI程序也肯定比命令行程序慢，每一行每一个字段值都是一个个可以在界面上操作的对象，生成这些有操作逻辑的对象肯定比生成纯文本的慢且耗费内存.
